// <auto-generated />
using System;
using AppIndumentaria.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppIndumentaria.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241125140330_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppIndumentaria.Models.Capacitacion", b =>
                {
                    b.Property<int>("CapacitacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CapacitacionID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CapacitacionID");

                    b.ToTable("Capacitaciones");
                });

            modelBuilder.Entity("AppIndumentaria.Models.Empleado", b =>
                {
                    b.Property<int>("EmpleadoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpleadoID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpleadoID");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("AppIndumentaria.Models.EntregaIndumentaria", b =>
                {
                    b.Property<int>("EntregaIndumentariaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntregaIndumentariaID"));

                    b.Property<int>("CantidadEntregada")
                        .HasColumnType("int");

                    b.Property<bool>("Certificacion")
                        .HasColumnType("bit");

                    b.Property<int>("EmpleadoID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<int>("IndumentariaID")
                        .HasColumnType("int");

                    b.Property<string>("TalleID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EntregaIndumentariaID");

                    b.HasIndex("EmpleadoID");

                    b.HasIndex("IndumentariaID");

                    b.HasIndex("TalleID");

                    b.ToTable("EntregasIndumentaria");
                });

            modelBuilder.Entity("AppIndumentaria.Models.Indumentaria", b =>
                {
                    b.Property<int>("IndumentariaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IndumentariaID"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IndumentariaID");

                    b.ToTable("Indumentarias");
                });

            modelBuilder.Entity("AppIndumentaria.Models.ParticipacionCapacitacion", b =>
                {
                    b.Property<int>("ParticipacionCapacitacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParticipacionCapacitacionID"));

                    b.Property<int>("CapacitacionID")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoID")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaParticipacion")
                        .HasColumnType("datetime2");

                    b.HasKey("ParticipacionCapacitacionID");

                    b.HasIndex("CapacitacionID");

                    b.HasIndex("EmpleadoID");

                    b.ToTable("ParticipacionesCapacitaciones");
                });

            modelBuilder.Entity("AppIndumentaria.Models.Talle", b =>
                {
                    b.Property<string>("TalleID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TalleID");

                    b.ToTable("Talles");
                });

            modelBuilder.Entity("AppIndumentaria.Models.TalleIndumentaria", b =>
                {
                    b.Property<int>("TalleIndumentariaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TalleIndumentariaID"));

                    b.Property<int>("CantidadDisponible")
                        .HasColumnType("int");

                    b.Property<int>("IndumentariaID")
                        .HasColumnType("int");

                    b.Property<string>("TalleID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TalleIndumentariaID");

                    b.HasIndex("IndumentariaID");

                    b.HasIndex("TalleID");

                    b.ToTable("TalleIndumentarias");
                });

            modelBuilder.Entity("AppIndumentaria.Models.EntregaIndumentaria", b =>
                {
                    b.HasOne("AppIndumentaria.Models.Empleado", "Empleado")
                        .WithMany("EntregasIndumentaria")
                        .HasForeignKey("EmpleadoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppIndumentaria.Models.Indumentaria", "Indumentaria")
                        .WithMany()
                        .HasForeignKey("IndumentariaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppIndumentaria.Models.Talle", "Talle")
                        .WithMany()
                        .HasForeignKey("TalleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Indumentaria");

                    b.Navigation("Talle");
                });

            modelBuilder.Entity("AppIndumentaria.Models.ParticipacionCapacitacion", b =>
                {
                    b.HasOne("AppIndumentaria.Models.Capacitacion", "Capacitacion")
                        .WithMany()
                        .HasForeignKey("CapacitacionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppIndumentaria.Models.Empleado", "Empleado")
                        .WithMany("ParticipacionesCapacitaciones")
                        .HasForeignKey("EmpleadoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capacitacion");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("AppIndumentaria.Models.TalleIndumentaria", b =>
                {
                    b.HasOne("AppIndumentaria.Models.Indumentaria", "Indumentaria")
                        .WithMany("TallesIndumentaria")
                        .HasForeignKey("IndumentariaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppIndumentaria.Models.Talle", "Talle")
                        .WithMany("TallesIndumentaria")
                        .HasForeignKey("TalleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Indumentaria");

                    b.Navigation("Talle");
                });

            modelBuilder.Entity("AppIndumentaria.Models.Empleado", b =>
                {
                    b.Navigation("EntregasIndumentaria");

                    b.Navigation("ParticipacionesCapacitaciones");
                });

            modelBuilder.Entity("AppIndumentaria.Models.Indumentaria", b =>
                {
                    b.Navigation("TallesIndumentaria");
                });

            modelBuilder.Entity("AppIndumentaria.Models.Talle", b =>
                {
                    b.Navigation("TallesIndumentaria");
                });
#pragma warning restore 612, 618
        }
    }
}
